[[llm]]

name = "deepseek"
base_url = "https://api.deepseek.com/v1"
api_key = "sk-xxx"
model = "deepseek-reasoner"

[memory]
file_path = "./AGENTS.md"

[[agent]]
compress_threshold = 0.8

[tools]
max_toolcall_token_in_round = 30000
