[[llm]]

name = "deepseek v3.2 reasoning"
base_url = "https://api.deepseek.com/v1"
api_key = "sk-xxx"
model = "deepseek-reasoner"

[[llm]]

name = "kimi"
base_url = "https://api.moonshot.cn/v1"
api_key = "sk-xxx"
model = "kimi-k2-turbo-preview"
compatibility = "kimi"

[agent]
compress_threshold_soft = 40000
compress_threshold_hard = 80000

[agent.tool_confirmation]

skip_confirmation = true

[memory]
file_path = "./LINHAI.md"

[tools]
max_output_length = 100000
