[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "linhai"
version = "0.1.0"
description = "AI Agent for software engineering and penetration testing"
authors = [
    {name = "LinHai"},
]
dependencies = [
    "openai",
    "httpx",
    "beautifulsoup4",
    "mistune",
    "textual",
    "selenium",
    "mcp",
    "pyte",
    "pydantic",
    "chardet",
    "bashlex",
    "tiktoken",
    "pillow",
    "tomli-w",
    "ether-ghost @ git+https://github.com/Marven11/EtherGhost.git@dev",
    "feedparser",
    "python-telegram-bot>=22.7",
    "quickjs-ng",
    "jinja2>=3.1.6",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pylint",
    "black",
    "pyright",
]

[project.scripts]
linhai = "linhai.main:main"

[dependency-groups]
dev = [
    "pyright>=1.1.407",
]
